APPLY_FIXES: all
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: false # Set to true to validate entire codebase
FILEIO_REPORTER: false
DISABLE_LINTERS:
  - PYTHON_PYLINT
  - PYTHON_BANDIT
  - PYTHON_PYRIGHT
  - PYTHON_MYPY
  - REPOSITORY_SEMGREP
  - SPELL_CSPELL
  - ACTION_ACTIONLINT
ACTION_ACTIONLINT_ARGUMENTS: -ignore "SC2086"
