# APPLY_FIXES: all
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
DISABLE_LINTERS:
  - PYTHON_PYLINT
  - PYTHON_BANDIT
  - PYTHON_MYPY
  - REPOSITORY_SEMGREP
  - SPELL_CSPELL
ACTION_ACTIONLINT_ARGUMENTS: -ignore "SC2086"