apiVersion: v1
kind: Pod
metadata:
  name: default_container
  namespace: airflow
  annotations: 
    iam.amazonaws.com/role: no_role
spec:
  containers:
    - name: default_python_pod
      image: 189157455002.dkr.ecr.eu-west-1.amazonaws.com/python:3.8-slim
      imagePullPolicy: IfNotPresent
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
