apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privilege-escalation
  annotations:
    policies.kyverno.io/title: Disallow Privilege Escalation
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.kyverno.io/description: >-
      Privilege escalation, such as via set-user-ID or set-group-ID file mode, should not be allowed.
      This policy ensures the `allowPrivilegeEscalation` field is set to `false`.
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: privilege-escalation
      context:
      - name: excluded-namespaces
        configMap:
          name: excluded-namespaces
          namespace: airflow
      match:
        any:
        - resources:
            kinds:
              - Pod
      preconditions:
      all:
      - key: "{{request.object.metadata.namespace}}"
        operator: AnyNotIn
        value: "{{excluded-namespaces.data.namespaces}}"
      validate:
        message: >-
          Privilege escalation is disallowed. The fields
          spec.containers[*].securityContext.allowPrivilegeEscalation,
          spec.initContainers[*].securityContext.allowPrivilegeEscalation,
          and spec.ephemeralContainers[*].securityContext.allowPrivilegeEscalation
          must be set to `false`.
        pattern:
          spec:
            =(ephemeralContainers):
            - =(securityContext):
                allowPrivilegeEscalation: "false"
            =(initContainers):
            - =(securityContext):
                allowPrivilegeEscalation: "false"
            =(containers):
            - =(securityContext):
                allowPrivilegeEscalation: "false"
