name: Lint
on:
  - pull_request
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check for flake8 config
        run: |
          if [ -e ./.flake8 ]; then
              echo "A .flake8 config file has been found in the root of this branch and will be used in this workflow."
          else
              echo "No .flake8 config file has been found in the root of this branch and so the standard Data Engineering config will used."
              curl https://moj-analytical-services.github.io/.github/configs/data-engineering/flake8 > .flake8
          fi
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint YAML files with yamllint
        run: >
          yamllint .
      - name: Check that Black would not make any changes to python files
        run: >
          black . --check
