name: Lint
on:
  - pull_request
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # >>> Install your own deps here (npm install, etc) <<<

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
