name: Pulumi Preview
on: pull_request
permissions:
  id-token: write
  contents: read
jobs:
  get-stacks:
    name: Get Stacks
    runs-on: ubuntu-latest
    outputs:
      STACKS: ${{ steps.get-stacks.outputs.STACKS }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Remove existing Pulumi installations
        run: |
          rm -rf $HOME/.pulumi
      - name: Install Pulumi CLI
        uses: moj-analytical-services/actions-setup-pulumi@main
      - name: Get Stacks
        id: get-stacks
        run: |
          echo "::set-output name=STACKS::$(find Pulumi.*.yaml | sed -ne "s/Pulumi\.\(.*\)\.yaml/\1/p" | jq --raw-input -cs 'split("\n") | map(select(. != ""))')"
        env:
          PULUMI_CONFIG_PASSPHRASE: ""
  preview-stack:
    name: Preview Stack
    needs: get-stacks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack: ${{ fromJson(needs.get-stacks.outputs.STACKS) }}
    steps:
      - name: do the pulumi preview
        uses: ministryofjustice/actions-pulumi@main
        with:
          stack: ${{ matrix.stack }}
          pulumi-action: preview
          backend-url: s3://alpha-mojap-de-courts-team/stephen/a-new-pulumi-test?profile=github-actions@data
          landing-arn: arn:aws:iam::335823981503:role/DataEngineeringGitHubActionIDRole20220907090933063600000002
          pulumi-passphrase: ""