name: Pulumi Preview
on:
  pull_request:
    branches:
      - main
permissions: read-all
env:
  AWS_ROLE_TO_ASSUME: arn:aws:iam::189157455002:role/github-actions-infrastructure
jobs:
  get-stacks:
    name: Get Stacks
    runs-on: [self-hosted, management-infrastructure]
    outputs:
      STACKS: ${{ steps.get-stacks.outputs.STACKS }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600
      - name: Remove existing Pulumi installations
        run: |
          rm -rf "$HOME/.pulumi"
      - name: Install Pulumi CLI
        uses: moj-analytical-services/actions-setup-pulumi@main
      - name: Get Stacks
        id: get-stacks
        run: |
          echo "STACKS=$(find Pulumi.*.yaml | sed -ne "s/Pulumi\.\(.*\)\.yaml/\1/p" | jq --raw-input -cs 'split("\n") | map(select(. != ""))')" >> $GITHUB_OUTPUT
        env:
          PULUMI_CONFIG_PASSPHRASE: ""
  preview-stack:
    name: Preview Stack
    needs: get-stacks
    runs-on: [self-hosted, management-infrastructure]
    strategy:
      fail-fast: false
      matrix:
        stack: ${{ fromJson(needs.get-stacks.outputs.STACKS) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Upgrade AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Remove existing Pulumi installations
        run: |
          rm -rf "$HOME/.pulumi"
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
        with:
          pulumi-version: ^3.0.0
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          if [ -f requirements.txt ]; then pip install --upgrade -r requirements.txt; fi
      - name: Preview changes
        env:
          PULUMI_CONFIG_PASSPHRASE: ""
        run: |
          pulumi stack select -c ${{ matrix.stack }}
          pulumi preview --refresh
