name: Pulumi Update
on:
  push:
    branches:
      - main
env:
  AWS_ROLE_TO_ASSUME: arn:aws:iam::189157455002:role/github-actions-infrastructure
jobs:
  get-stacks:
    name: Get Stacks
    runs-on: [self-hosted, management-infrastructure]
    outputs:
      STACKS: ${{ steps.get-stacks.outputs.STACKS }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600
      - name: Remove existing Pulumi installations
        run: |
          rm -rf $HOME/.pulumi
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - name: Get Stacks
        id: get-stacks
        run: |
          echo "dev"
        env:
          PULUMI_CONFIG_PASSPHRASE: ""
  update-stack:
    name: Update Stack
    needs: get-stacks
    runs-on: [self-hosted, management-infrastructure]
    strategy:
      fail-fast: false
      matrix:
        stack: ${{ fromJson(needs.get-stacks.outputs.STACKS) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Remove existing Pulumi installations
        run: |
          rm -rf $HOME/.pulumi
      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install --upgrade -r requirements.txt; fi
      - name: Deploy changes
        env:
          PULUMI_CONFIG_PASSPHRASE: ""
        run: |
          pulumi stack select -c ${{ matrix.stack }}
          pulumi up --refresh --yes --skip-preview
